apiVersion: apps/v1
kind: Deployment
metadata:
  name: ServiceName
  labels:
    app: ServiceName
    deployon: "dsr"
    nwpolicy: bytefunctionexecer-access
spec:
  replicas: replace_replicas
  selector:
    matchLabels:
      app: ServiceName
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ServiceName
        deployon: "dsr"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ServiceName
                topologyKey: "kubernetes.io/hostname"
      containers:
        - image: image_to_be_deployed
          imagePullPolicy: Always
          name: ServiceName
          ports:
            - containerPort: 9301
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9301
            initialDelaySeconds: 120
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9301
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: JAEGER_COLLECTOR_URL
              valueFrom:
                configMapKeyRef:
                  name: edishipstatuslistener-configmap
                  key: jaeger.collector.url
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-urls
                  key: edicoredata.mongodb.url
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: SvcName
  labels:
    app: ServiceName
    k8s-app: bytefunctionexecer
spec:
  selector:
    app: ServiceName
  type: ClusterIP
  ports:
    - port: 9301
      name: web
      targetPort: 9301
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bytefunctionexecer
spec:
  maxReplicas: replace_maxReplicas
  minReplicas: replace_minReplicas
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpaSrvName
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70