management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,env,httptrace,loggers

spring:
  zipkin:
    base-url: ${JAEGER_COLLECTOR_URL}
    service:
      name: bytefunctionexecer
    enabled: true
  sleuth:
    opentracing:
      enabled: true
    trace-id128: true
    sampler:
      probability: 1.0
  codec:
    max-in-memory-size: 10MB

logging:
  level:
    ROOT: INFO
    org.springframework.data.mongodb: DEBUG